#!/usr/bin/env python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from __future__ import print_function
import optparse
from proton.handlers import MessagingHandler
from proton.reactor import Container

class Recv(MessagingHandler):
    def __init__(self, server, addresses):
        super(Recv, self).__init__()
        self.server = server
        self.addresses = addresses or ["hello"]

    def on_start(self, event):
        conn = event.container.connect(self.server)
        for address in self.addresses:
            event.container.create_receiver(conn, address)

    def on_message(self, event):
        print("%s: %s" % (event.link.source.address, event.message.body))

parser = optparse.OptionParser(usage="usage: %prog [options]")
parser.add_option("-s", "--server", default="localhost:5672",
                  help="server to connect to (default %default)")
parser.add_option("-a", "--address", default=[], action="append",
                  help="address to subscribe to (default %default)")
opts, args = parser.parse_args()

try:
    Container(Recv(opts.server, opts.address)).run()
except KeyboardInterrupt: pass



